### ISSUE TITLE
Customer không có metafields?

### ISSUE THREAD

**Issue by lucreck** [Haravan/haravan-node-api#1]
Hiện tại mình khởi tạo customer kèm metafields thì không thấy metafields được lưu. Bác nào biết tại sao không? Mình đã thử với product thì ok.
<img width="868" alt="screen shot 2017-11-26 at 7 58 21 pm" src="https://user-images.githubusercontent.com/7540383/33240163-5aacb566-d2e4-11e7-8aa4-41b38f6206ca.png">

**Comment by lmcuong29** [comment]
Hi lucreck,

API chưa hỗ trợ post metafield trực tiếp như vậy. Hãy dùng API metafield để post nhé

https://docs.haravan.com/blogs/api-reference/1000018026-metafield
