### ISSUE TITLE
Tạo sản phẩm mới nhưng bị miss ảnh

### ISSUE THREAD

**Issue by lucreck** [Haravan/haravan-node-api#2]
Hiện tại bên em đang gặp hiện tượng tạo sản phẩm qua api nhưng không nhận ảnh. Không biết bên mình có thay đổi thông tin gì không a

<img width="824" alt="screen shot 2019-02-19 at 11 17 29" src="https://user-images.githubusercontent.com/7540383/52989900-1bc1a800-3438-11e9-9452-26e8f25d5d85.png">

**Comment by lmcuong25** [comment]
Hi Lucreck,

Việc tạo ảnh trước tiếp trong api product không hỗ trợ nữa. 

thay vào đó thì dùng API image riêng :  https://docs.haravan.com/blogs/api-reference/1000085504-product-image

**Comment by lucreck** [comment]
Okie a 👌
